config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#home"
  get "/home" => "home#home", as: :home

  get "/about" => "home#about", as: :about

  get '/auth/twitter', as: :sign_in_with_twitter
  get '/auth/twitter/callback' => 'callbacks#twitter'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts, only: [:create, :index, :show]
    end
  end

  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :favourites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :new, :create, :edit, :update]
  # UPDATE USER
  get "users/:id/password" => "users#edit_password", as: :user_password
  patch "users/:id/password" => "users#update_password"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true, uniqueness: {scope: :post_id}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]

  def new
      @comment = Comment.new
    end

  def create
    puts "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
    @comment = Comment.new

    p @comment



    p "current user method: "
    p current_user
    @comment.user = current_user
    p "current user: "
    p @comment.user
    @comment = Comment.new params.require(:comment).permit(:title, :body)
    @post = Post.find params[:post_id]
    @comment.post = @post

    respond_to do |format|
      if @comment.save
        format.html {redirect_to post_path(@post), notice: "Comment created" }
        format.js { render :create_success }
      else
        flash[:alert] = "Please fix errors below"
        format.html {render "/posts/show"}
        format.js { render :create_failure }
      end
    end

  end

  def destroy
    post = Post.find params[:post_id]
    comment = Comment.find params[:id]
    comment.destroy
    redirect_to post_path(post), notice: "Comment deleted"
  end

  def show
    @post = Post.find params[:post_id]
    @comment = Comment.find params[:id]
  end

  def index
    @comments = Comment.order(created_at: :desc)
  end


  def edit
    @post = Post.find params[:post_id]
    @comment = Comment.find params[:id]
  end

  def update
    @post = Post.find params[:post_id]
    @comment = Comment.find params[:id]
    if @comment.update comment_params
      redirect_to post_comment_path(@post.id)
    else
      render :edit
    end
  end

  private
  def comment_params
  params.require(:comment).permit(:title, :body)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%# comment.user.first_name%>
<%= comment.title %>
<%= comment.body %>
<%= link_to "Edit", edit_post_comment_path(@post, comment),
                    class: "btn btn-default" %>
<%= link_to "Delete", post_comment_path(@post, comment),
                    method: :delete,
                    data: {confirm: "Are you sure you want to delete this comment?"},
                    class: "btn btn-default"%>
<hr>

app/views/comments/create_success.html.erb
$('#comments').prepend('<%= j(render('/comments/comment', {comment: @comment})) %>');

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= @comment.errors.full_messages.join(", ") %>
<%= form_for [@post,@comment]  do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <%= f.submit,'Save', post_path(@post) %>

<% end %>

app/views/comments/index.html.erb
<!-- <h1>Comments</h1>
<% @comments.each do |comment| %>
<div>
<%= link_to comment.title, comment_path(comment)%>
</div>

<% end %> -->

app/views/comments/new.html.erb
<h1><i class="fa fa-reply" aria-hidden="true"></i>&nbspCreate a New Comment</h1>
<%= @comment.errors.full_messages.join(", ") %>
<%= form_for @comment do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <%= f.submit %>

<% end %>