config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#home"
  get "/home" => "home#home", as: :home

  get "/about" => "home#about", as: :about

  get '/auth/twitter', as: :sign_in_with_twitter
  get '/auth/twitter/callback' => 'callbacks#twitter'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts, only: [:create, :index, :show]
    end
  end

  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :favourites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :new, :create, :edit, :update]
  # UPDATE USER
  get "users/:id/password" => "users#edit_password", as: :user_password
  patch "users/:id/password" => "users#update_password"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/post.rb
class Post < ApplicationRecord
  attr_accessor :tweet_it

  has_many :comments, dependent: :destroy

  has_many :favourites, dependent: :destroy
  has_many :users, through: :favourites

  belongs_to :user
  validates :title, presence: true, length: {minimum: 7}, uniqueness: {scope: :body}
  validates :body, presence: true

  def favourite_for(user)
    favourites.find_by_user_id user
  end

  def body_snippet(body)
    body.slice(0,100) + "..."
  end


end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController

  def index
    @posts = Post.order(created_at: :desc)
    render json: @posts
  end

  def show
    @user = User.new
    @post = Post.find params[:id]
    @comment = Comment.new
    render json: @post
  end

  def create
    # post_params  = params.require(:post).permit([:title, :body])
    @post       = Post.new post_params
    @post.user = current_user

    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]

POSTS_PER_PAGE=5

  def new
      @post = Post.new
    end

    def create
      # post_params  = params.require(:post).permit([:title, :body])
      @post       = Post.new post_params
      @post.user = current_user

      if @post.save
        if @post.tweet_it
        client = Twitter::REST::Client.new do |config|
        config.consumer_key        = ENV["TWITTER_API_KEY"]
        config.consumer_secret     = ENV["TWITTER_API_SECRET"]
        config.access_token        = current_user.twitter_token
        config.access_token_secret = current_user.twitter_secret
      end
        client.update "#{@post.title} #{post_url(@post)}"
      end

        redirect_to post_path(@post)
      else
        render :new
      end
    end

    def show
      @user = User.new
      @post = Post.find params[:id]
      @comment = Comment.new
    end

    def index
      @posts = Post.order(created_at: :desc).page(params[:page]).per(POSTS_PER_PAGE)
    end

    def destroy
      # post = Post.find params[:id]
      # post.destroy
      @post.destroy
      redirect_to posts_path
    end

    def edit
      @post = Post.find params[:id]
    end

    def update
      @post = Post.find params[:id]
      if @post.update post_params
        redirect_to post_path(@post)
      else
        render :edit
      end
    end

    private
    def post_params
    params.require(:post).permit(:title, :body, :tweet_it)
    end

end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= @post.errors.full_messages.join(", ") %>
<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <%= f.submit %>

<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<% @posts.each do |post| %>
<div>
<%= link_to post.title, post_path(post)%>
</div>

<% end %>  


<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= @post.errors.full_messages.join(", ") %>
<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div>
    <% if current_user.from_twitter? %>
    <%= f.label :tweet_it%>
    <%= f.check_box :tweet_it, as: :boolean  %>
    <% end %>
  </div>

  <%= f.submit %>

<% end %>

app/views/posts/show.html.erb
<div>

<h4><%= @post.user.first_name.capitalize%>'s Question</h4>
<hr>
<h1><%= @post.title %></h1>
<p>
  <%= @post.body %>
</p>

<%= link_to "Edit", edit_post_path(@post), class: "btn btn-default" %>
<%= link_to "Delete", post_path(@post),
                    method: :delete,
                    data: {confirm: "Are you sure you want to delete this post?"},
                    class: "btn btn-default"%>

<!-- Favourite  -->
<% if can? :favourite, @post %>
<% user_favourite = @post.favourite_for current_user %>
<% if user_favourite.present? %>
<i class="fa fa-thumbs-o-down" aria-hidden="true"></i>
<%= link_to "Unfavourite", post_favourite_path(@post, user_favourite),
                            method: :delete,
                            class: "btn btn-default" %>
<% else %>
<div class: "btn btn-default">
<i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
<%= link_to "Favourite", post_favourites_path(@post),
                          method: :post%>
</div>
<% end %>
<% else %>
<i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
Favourite
<% end %>
(<%= pluralize @post.favourites.count, "favourite" %>)

<hr>

<!-- Comments create-->
<h1><i class="fa fa-reply" aria-hidden="true"></i>&nbspCreate a New Comment</h1>
<%= @comment.errors.full_messages.join(", ") %>
<%= form_for [@post, @comment], remote: true do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <%= f.submit%>

<% end %>

<hr>
<!-- Comments show -->
<h2>All Comments</h2>
<div id="comments">
<% @post.comments.each do |comm| %>
<%# comm.user.first_name%>
<%# comm.title %>
<%# comm.body %>
<%# link_to "Edit", edit_post_comment_path(@post, comm) %>
<%# link_to "Delete", post_comment_path(@post, comm),
                    method: :delete,
                    data: {confirm: "Are you sure you want to delete this comment?"}%>
<!-- <hr> -->
<%= render "/comments/comment", comment: comm %>
<% end %>
</div>

</div>