config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#home"
  get "/home" => "home#home", as: :home

  get "/about" => "home#about", as: :about

  get '/auth/twitter', as: :sign_in_with_twitter
  get '/auth/twitter/callback' => 'callbacks#twitter'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts, only: [:create, :index, :show]
    end
  end

  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :favourites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :new, :create, :edit, :update]
  # UPDATE USER
  get "users/:id/password" => "users#edit_password", as: :user_password
  patch "users/:id/password" => "users#update_password"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://use.fontawesome.com/49f2f34f72.js"></script>
</head>

<body>
  <nav class="navbar navbar-custom navbar-fixed-top">
    <div class="container">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>

        <li><%= link_to "About", about_path %></li>

        <li><%= link_to "New Post", new_post_path %></li>
        <!-- All Posts Dropdown -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">All Posts <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Posts", posts_path %></a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">My Posts</a></li>
            <li><a href="#">My comments</a></li>
          </ul>
        </li>

        <% if user_signed_in? %>
        <li class="w_padding"> Welcome <%= current_user.full_name %>! </li>
        <!-- User Account Dropdown -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit", edit_user_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Sign Out", sessions_path, method: :delete %></li>
          </ul>
        </li>
        <% else  %>

        <li><%= link_to "Sign up", new_user_path %></li>
        <li><%= link_to "Sign In", new_session_path %></li>
        <li><%= link_to "Sign In with Twitter", sign_in_with_twitter_path %></li>
        <% end %>

      </ul>


    </div>
  </nav>

  <%= flash[:notice] || flash[:alert]%>

  <div class="yield">
    <%= yield %>
  </div>
</body>
</html>